# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class MotifUtils(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def UploadFromGibbs(self, params, context=None):
        """
        :param params: instance of type "UploadMEMEInParams" -> structure:
           parameter "path" of String, parameter "ws_name" of String,
           parameter "obj_name" of String
        :returns: instance of type "UploadOutput" -> structure: parameter
           "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.UploadFromGibbs',
            [params], self._service_ver, context)

    def UploadFromHomer(self, params, context=None):
        """
        :param params: instance of type "UploadHomerInParams" -> structure:
           parameter "path" of String, parameter "ws_name" of String,
           parameter "obj_name" of String, parameter "location_path" of String
        :returns: instance of type "UploadOutput" -> structure: parameter
           "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.UploadFromHomer',
            [params], self._service_ver, context)

    def UploadFromMEME(self, params, context=None):
        """
        :param params: instance of type "UploadGibbsInParams" -> structure:
           parameter "path" of String, parameter "ws_name" of String,
           parameter "obj_name" of String
        :returns: instance of type "UploadOutput" -> structure: parameter
           "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.UploadFromMEME',
            [params], self._service_ver, context)

    def UploadFromJASPAR(self, params, context=None):
        """
        :param params: instance of type "UploadJASPARInParams" -> structure:
           parameter "path" of String, parameter "ws_name" of String,
           parameter "obj_name" of String
        :returns: instance of type "UploadOutput" -> structure: parameter
           "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.UploadFromJASPAR',
            [params], self._service_ver, context)

    def UploadFromTRANSFAC(self, params, context=None):
        """
        :param params: instance of type "UploadTRANSFACInParams" ->
           structure: parameter "path" of String, parameter "ws_name" of
           String, parameter "obj_name" of String
        :returns: instance of type "UploadOutput" -> structure: parameter
           "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.UploadFromTRANSFAC',
            [params], self._service_ver, context)

    def DownloadMotifSet(self, params, context=None):
        """
        :param params: instance of type "DownloadParams" -> structure:
           parameter "ws_name" of String, parameter "source_ref" of String,
           parameter "format" of String
        :returns: instance of type "DownloadOutput" -> structure: parameter
           "destination_dir" of String
        """
        return self._client.call_method(
            'MotifUtils.DownloadMotifSet',
            [params], self._service_ver, context)

    def importFromNarrative(self, params, context=None):
        """
        :param params: instance of type "ImportNarrativeInParams" ->
           structure: parameter "ws_name" of String, parameter "path" of
           String, parameter "format" of String, parameter "obj_name" of
           String
        :returns: instance of type "ImportNarrativeOutParams" -> structure:
           parameter "obj_ref" of String
        """
        return self._client.call_method(
            'MotifUtils.importFromNarrative',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('MotifUtils.status',
                                        [], self._service_ver, context)
